In [1]:
# Sudenaz Yazıcı - 2210356008
import pandas as pd
import numpy as np
import math
df = pd.read_csv('16P.csv',encoding = "cp1252")
print(df)

       Response Id  You regularly make new friends.  \
0                0                                0   
1                1                                0   
2                2                                0   
3                3                                0   
4                4                                0   
...            ...                              ...   
59994        59994                                0   
59995        59995                                0   
59996        59996                                0   
59997        59997                                0   
59998        59998                                0   

       You spend a lot of your free time exploring various random topics that pique your interest  \
0                                                      0                                            
1                                                      0                                            
2                                   

In [2]:
df.pop("Response Id")
print(df)

       You regularly make new friends.  \
0                                    0   
1                                    0   
2                                    0   
3                                    0   
4                                    0   
...                                ...   
59994                                0   
59995                                0   
59996                                0   
59997                                0   
59998                                0   

       You spend a lot of your free time exploring various random topics that pique your interest  \
0                                                      0                                            
1                                                      0                                            
2                                                      0                                            
3                                                     -1                                   

In [3]:

df["Personality"] = df["Personality"].replace(["ESTJ"],0)
df["Personality"] = df["Personality"].replace(["ENTJ"],1)
df["Personality"] = df["Personality"].replace(["ESFJ"],2)
df["Personality"] = df["Personality"].replace(["ENFJ"],3)
df["Personality"] = df["Personality"].replace(["ISTJ"],4)
df["Personality"] = df["Personality"].replace(["ISFJ"],5)
df["Personality"] = df["Personality"].replace(["INTJ"],6)
df["Personality"] = df["Personality"].replace(["INFJ"],7)
df["Personality"] = df["Personality"].replace(["ESTP"],8)
df["Personality"] = df["Personality"].replace(["ESFP"],9)
df["Personality"] = df["Personality"].replace(["ENTP"],10)
df["Personality"] = df["Personality"].replace(["ENFP"],11)
df["Personality"] = df["Personality"].replace(["ISTP"],12)
df["Personality"] = df["Personality"].replace(["ISFP"],13)
df["Personality"] = df["Personality"].replace(["INTP"],14)
df["Personality"] = df["Personality"].replace(["INFP"],15)
print(df)

       You regularly make new friends.  \
0                                    0   
1                                    0   
2                                    0   
3                                    0   
4                                    0   
...                                ...   
59994                                0   
59995                                0   
59996                                0   
59997                                0   
59998                                0   

       You spend a lot of your free time exploring various random topics that pique your interest  \
0                                                      0                                            
1                                                      0                                            
2                                                      0                                            
3                                                     -1                                   

In [4]:
test = df.drop("Personality",axis = 1)
test = test.to_numpy()
df = df.to_numpy()
print(df)
print(test)

[[ 0  0  0 ...  0  0 11]
 [ 0  0 -2 ... -1  3 13]
 [ 0  0  2 ...  2  1  7]
 ...
 [ 0  0  1 ...  0 -1 12]
 [ 0  0  1 ...  1  0  4]
 [ 0  0  2 ...  0 -1  7]]
[[ 0  0  0 ...  0  0  0]
 [ 0  0 -2 ... -1 -1  3]
 [ 0  0  2 ...  1  2  1]
 ...
 [ 0  0  1 ... -1  0 -1]
 [ 0  0  1 ...  0  1  0]
 [ 0  0  2 ...  1  0 -1]]


In [5]:
training_data1 = test[:9600]
testing_data1 = test[9600:12000]
training_data2 = test[12000:21600]
testing_data2 = test[21600:24000]
training_data3 = test[24000:33600]
testing_data3 = test[33600:36000]
training_data4 = test[36000:45600]
testing_data4 = test[45600:48000]
training_data5 = test[48000:57600]
testing_data5 = test[57600:]

print("Shape of training examples: {}".format(training_data1.shape))
print("Shape of test examples: {}".format(testing_data1.shape))

Shape of training examples: (9600, 60)
Shape of test examples: (2400, 60)


In [6]:
result1 = []
for i in testing_data1:
    test1 = np.subtract(training_data1,i)
    #print(len(test1))
    test1 = np.squeeze(test1)
    #print(len(test1))
    test1 = np.multiply(test1,test1)
    #print(test1)
    result1.append(test1.sum(axis = 1)**1/2)  # result1's items are the distances
print(len(result1[0]))
print(result1)

9600
[array([ 64.5, 128. ,  73.5, ...,  93.5, 115.5,  99.5]), array([ 59.5,  79. ,  78.5, ...,  96.5, 128.5,  84.5]), array([ 49.5, 117. ,  96.5, ...,  88.5,  85.5,  94.5]), array([ 54.5, 112. ,  97.5, ...,  71.5, 125.5, 122.5]), array([ 69. , 114.5,  65. , ...,  97. , 110. ,  94. ]), array([ 58. ,  68.5,  80. , ..., 107. , 118. ,  95. ]), array([ 68. ,  92.5,  64. , ...,  93. , 104. ,  84. ]), array([54.5, 87. , 83.5, ..., 88.5, 82.5, 74.5]), array([ 60. , 131.5,  87. , ..., 115. , 120. ,  51. ]), array([ 51. ,  95.5,  85. , ..., 100. ,  94. , 104. ]), array([ 45. ,  79.5,  97. , ...,  86. , 111. ,  76. ]), array([ 63.5, 131. , 100.5, ...,  72.5, 118.5, 137.5]), array([ 49.5,  48. ,  74.5, ...,  87.5, 102.5,  66.5]), array([ 50. ,  94.5,  78. , ...,  85. ,  91. , 109. ]), array([ 54.5,  83. ,  65.5, ...,  93.5, 107.5,  84.5]), array([ 60. , 131.5,  80. , ...,  45. ,  76. , 117. ]), array([ 45. , 125.5,  77. , ...,  69. , 110. ,  80. ]), array([ 74.5,  59. , 106.5, ..., 111.5, 159.5,  

In [7]:
#print(result1.index(min(result1)))
# for k = 1
tp1, tn1,fn1, fp1  = 0,0,0,0

for i in result1:
    i = i.reshape(1,9600)
    i = pd.DataFrame(i)
    #print(i)
    #min_val = min(i)
    #testing_data1["Personality"] == training_data1[i.iloc(min(i))]
    print(training_data1[i.index(min(i))])
print(testing_data1)

TypeError: 'RangeIndex' object is not callable

<font color=red>ERROR ANALYSIS </font> 
* For k = 1, there will be no problem. However, for k>1, if there are equal numbered classes in closest k classes, classification will be random. For instance, let k be 5; if two of these classes are "ENSTJ" and two of these classes are "INFP", the machine cannot decide the class or assign it randomly.

I could not complete the algorithm, but my aim was to find the results index. Through this index, we could assign the testing_data's "Personality" column same as the k nearest data. Then, we could compare the personalities that we find and the actual personalities. 